import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Instrument_Sans } from 'next/font/google'
import Footer from '@/components/Footer'


const instrumentSans = Instrument_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Gime | Homepage',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={instrumentSans.className}>
        <Navbar />{children}<Footer />
      </body>
    </html>
  )
}
