import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";

import Footer from "@/components/Footer";
import Dialog from "@/components/ui/Dialog";
import Head from "next/head";

const instrumentSans = Instrument_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gime | Homepage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </Head>
      <body className={instrumentSans.className}>
        <Dialog />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
